### PR TITLE
Initial attempt at setting up astro

### PR DESCRIPTION
**Pull request by jasikpark**
I'm excited to see how Astro matches up to the other SSG's! Let me know if there's anything I need to fix, I tried to follow microsites's config for the most part - @natemoo-re strikes again working on another ssg :D

https://astro.build/chat for the discord

### CODE REVIEW

**Comment by seancdavis** [comment]
@jasikpark Thanks for this! I'm a big fan of what Astro is working on. Curious to see how it stacks up here.

I ran the dev (super small) job manually and it looks good. Going to merge and then run the larger jobs and see if it can handle them.

**Comment by jasikpark** [comment]
Awesome! I'm really excited to see how it stacks up now & how it improves in the coming months!

**Comment by jasikpark** [comment]
Hmm is Astro failing at the highest file count? Or is it just suddenly getting **really** magically efficient? 😅

image

**Comment by seancdavis** [comment]
@jasikpark Yeah, seems to be having some issues. I created #74 with further details.

**Pull request merged**
