### PR TITLE
Add Microsite

### PR DESCRIPTION
**Pull request by natemoo-re**
👋  Hey there—thanks for the incredibly helpful tool! This PR adds [Microsite](https://github.com/natemoo-re/microsite) to the mix. It's built on top of Preact, so I think it's fair to consider it a `framework` SSG, but feel free to remove that flag if you disagree.

One note: I didn't see a node version in the machine specs or any mention of `.nvmrc`/`volta` in the codebase, so I'm not sure what version of Node this runs on. Microsite uses ESM via `type: module` in `package.json`, so it expects node@12.19+

I was able to reverse engineer your Hasura setup to run this locally, but it was pretty difficult. It might be nice to remove the Hasura dependency for local builds to make it easier to contribute.

### CODE REVIEW

**Comment by seancdavis** [comment]
Hi @natemoo-re! Thank you for opening this PR!

I added issue #26 to ensure you can run builds locally while developing. I'll get the README updated as a result. I'm also working on automating the test builds, which is currently brittle. This is happening in #25.

I'm hoping to give this some attention over the coming weeks and get this all cleaned up so we can add Microsite!

In the meantime, I can tell you that I'll make sure we are running Node v12+ as part of the work on #25.

**Comment by natemoo-re** [comment]
Awesome, thanks @seancdavis! I'll keep an eye out for those changes and give this another pass after. 😄

**Comment by seancdavis** [comment]
@natemoo-re I still have a bit of cleanup to do, but the important pieces are in place. Please see updated documentation in the README and then we'll get Microsite added. Let me know if you have any questions as you dig in.

**Comment by natemoo-re** [comment]
Hey @seancdavis—the new `--dryrun` flag is great! I think this is ready for your review!

**Comment by natemoo-re** [comment]
Thanks so much!

**Comment by seancdavis** [comment]
Thank you for the contribution! Love adding to this.

**Pull request merged**
