### PR TITLE
Add mkws

### PR DESCRIPTION
**Pull request by adriangrigore**

### CODE REVIEW

**Comment by jasikpark** [comment]
https://mkws.sh/ 🤔

**Comment by adriangrigore** [comment]
> https://mkws.sh/ 🤔

Yup!

**Comment by adriangrigore** [comment]
Hold on, I have to add generating `sitemap.xml`. I thought `hugo` doesn't generate one so I removed it.

**Comment by adriangrigore** [comment]
Done!

**Pull request closed without merging**
